### ISSUE TITLE
[Back end] Permission system

### ISSUE THREAD

**Issue by nguyenmanhdang90** [our-fancy-team-name/office-space#19]
We need a clear design about how we handle permission.
ideally, it will contain at least two-level, group level and personal level
This is considered as a business analyst task and database design as well
On the back end, we must find a way to use spring features to reduce the code required to check permission.

**Comment by nguyenmanhdang90** [comment]
https://en.wikipedia.org/wiki/Role-based_access_control
Basically we will have 3 concept
User (U)
Role (R)
Permission (P)

Following by 3 rules
1/ A Role map with multiple Permissions
2/ An User map with multiple Roles
3/ On a session of User, there only 1 Roles can be active at a time. 
  An exmple: a user with 2 roles hr and dev. Hr can view salary but dev cannot. When user using the app with hr role user can view salary, if user change perspective to dev they wont see salary anymore.

**Comment by khaihq94** [comment]
How can we define which role will be used when a user logs in? We will have a page for choosing role? Or what is your idea?

**Comment by nguyenmanhdang90** [comment]
![image](https://user-images.githubusercontent.com/7055196/76511691-16d9f700-6486-11ea-8100-1b78b36b9ca4.png)

**Comment by khaihq94** [comment]
Ok, first time I see it. I think it's ok for now
